Repository hack4impact-uiuc/south-side-weekly, pull requests merged in 2021-06, with the labels that each got.

#82 Update README.md
  README.md
Labels: documentation

#84 Remove hooks and husky dependencies
  package.json
  yarn.lock
Labels: devops

#86 📁 Restructure API wrapper
  client/src/api/auth/index.ts
  client/src/api/auth/types.ts
  client/src/api/builders.ts
  client/src/api/index.ts
  client/src/api/pitch/index.ts
  client/src/api/pitch/types.ts
  client/src/api/resource/index.ts
  client/src/api/resource/types.ts
  client/src/api/types.ts
  client/src/api/urls.ts
  client/src/api/user/index.ts
  client/src/api/user/types.ts
  client/src/components/PitchDoc/ClaimPitchModal.tsx
  client/src/components/ResourceHub/AddResourceModal.tsx
  client/src/components/ResourceHub/EditResourceModal.tsx
  client/src/components/Sidebar.tsx
  client/src/pages/Directory.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/pages/ResourcePage.tsx
  client/src/pages/pitchDoc/PitchDoc.tsx
  client/src/pages/profile/Profile.tsx
  client/src/utils/apiHelpers.ts
  client/src/utils/apiWrapper.ts
Labels: frontend

#83 🔒 Add Admin-only restricted fields
  api/package.json
  api/src/api/users.ts
  api/src/auth/authmiddleware.ts
  api/src/auth/authvalidators.ts
  api/src/middleware/auth.ts
  api/src/utils/auth-utils.ts
  api/src/utils/user-utils.ts
  api/yarn.lock
  client/cypress/videos/homepage_spec.js.mp4
  client/src/api/index.ts
  client/src/api/user/index.ts
  client/src/api/user/types.ts
  client/src/components/UserModal/UserModal.tsx
  client/src/pages/profile/Profile.tsx
  client/yarn.lock
  package-lock.json
  package.json
  yarn.lock
Labels: fullstack

#94 ⏩ Automate Express Restart
  api/package.json
Labels: backend
