Repository hack4impact-uiuc/south-side-weekly, pull requests merged in 2021-03, with the labels that each got.

#24 Add initial User Schema and GET, POST, PUT, DELETE Endpoints
  api/src/api/users.ts
  api/src/models/pitch.ts
  api/src/models/user.ts
  api/test/home.test.js
  api/test/users.test.js
Labels: Backend

#35 Add Support for Semantic UI React
  client/package.json
  client/src/index.tsx
  client/yarn.lock
Labels: Frontend

#26 Onboarding Wizard 🧙
  client/package.json
  client/src/assets/arrow-back.svg
  client/src/assets/arrow-next.svg
  client/src/assets/basic-info.svg
  client/src/assets/check.svg
  client/src/assets/completion-page.svg
  client/src/assets/info.svg
  client/src/assets/involvement-page.svg
  client/src/assets/onboard5.svg
  client/src/assets/onboard6.svg
  client/src/assets/onboard7.svg
  client/src/assets/onboard8.svg
  client/src/assets/personal-information.svg
  client/src/assets/races-page.svg
  client/src/assets/required.svg
  client/src/assets/role-page.svg
  client/src/assets/ssw-form-header.png
  client/src/components/WizardPageCounter/WizardPageCounter.tsx
  client/src/components/WizardSelectButton/WizardSelectButton.tsx
  client/src/css/WizardSelectButton.css
  client/src/css/index.css
  client/src/css/wizard/Completion.css
  client/src/css/wizard/InitialPrompt.css
  client/src/css/wizard/Onboard1.css
  client/src/css/wizard/Onboard2.css
  client/src/css/wizard/Onboard3.css
  client/src/css/wizard/Onboard4.css
  client/src/css/wizard/Onboard5.css
  client/src/css/wizard/Onboard6.css
  client/src/css/wizard/Onboard7.css
  client/src/css/wizard/Onboard8.css
  client/src/css/wizard/WizardPageCounter.css
  client/src/css/wizard/WizardWrapper.css
  client/src/index.tsx
  client/src/pages/Home.tsx
  client/src/pages/wizard/Completion.tsx
  client/src/pages/wizard/InitialPrompt.tsx
  client/src/pages/wizard/Onboard1.tsx
  client/src/pages/wizard/Onboard2.tsx
  client/src/pages/wizard/Onboard3.tsx
  client/src/pages/wizard/Onboard4.tsx
  client/src/pages/wizard/Onboard5.tsx
  client/src/pages/wizard/Onboard6.tsx
  client/src/pages/wizard/Onboard7.tsx
  client/src/pages/wizard/Onboard8.tsx
  client/src/pages/wizard/WizardWrapper.tsx
  client/src/utils/helpers.tsx
  client/yarn.lock
Labels: Frontend

#37 Resource Page 📚
  client/src/assets/resource-page.svg
  client/src/css/Resource.css
  client/src/index.tsx
  client/src/pages/Home.tsx
  client/src/pages/ResourcePage.tsx
  client/yarn.lock
Labels: Frontend

#41 Add Resource model and GET, POST, PUT, DELETE endpoints
  api/src/api/index.ts
  api/src/api/resources.ts
  api/src/models/resource.ts
Labels: Backend

#44 Onboarding Wizard Confirmation Modal
  client/src/assets/close.svg
  client/src/components/WizardPageCounter/WizardPageCounter.tsx
  client/src/css/wizard/Onboard8.css
  client/src/css/wizard/WizardPageCounter.css
  client/src/pages/wizard/InitialPrompt.tsx
  client/src/pages/wizard/Onboard5.tsx
  client/src/pages/wizard/Onboard8.tsx
  client/src/pages/wizard/WizardWrapper.tsx
Labels: frontend

#43 Integrate Auth frontend + backend
  .github/workflows/api.yaml
  api/package.json
  api/src/api/auth.ts
  api/src/api/index.ts
  api/src/app.ts
  api/src/auth/authmiddleware.ts
  api/src/auth/authvalidators.ts
  api/src/models/user.ts
  api/src/types/index.d.ts
  api/src/utils/helpers.ts
  api/src/utils/passport-setup.ts
  api/tsconfig.json
  api/yarn.lock
  client/package.json
  client/src/css/Home.css
  client/src/css/Login.css
  client/src/index.tsx
  client/src/pages/Home.tsx
  client/src/pages/Login.tsx
  client/src/utils/apiHelpers.ts
  client/src/utils/apiWrapper.ts
  client/src/utils/enums.ts
  client/yarn.lock
Labels: fullstack

#36 Aj/profile
  client/src/assets/banner.svg
  client/src/assets/fold.zip
  client/src/assets/fold/globe.svg
  client/src/assets/fold/linkedin.svg
  client/src/assets/fold/mail.svg
  client/src/assets/fold/phone.svg
  client/src/assets/fold/twitter.svg
  client/src/assets/globe.png
  client/src/assets/globe.svg
  client/src/assets/home.svg
  client/src/assets/library.svg
  client/src/assets/linkedin.png
  client/src/assets/linkedin.svg
  client/src/assets/mail.png
  client/src/assets/mail.svg
  client/src/assets/mail2.svg
  client/src/assets/masthead.svg
  client/src/assets/people.svg
  client/src/assets/person.svg
  client/src/assets/pfp.svg
  client/src/assets/phone.png
  client/src/assets/phone.svg
  client/src/assets/pitch.svg
  client/src/assets/twitter.png
  client/src/assets/twitter.svg
  client/src/components/Sidebar.tsx
  client/src/css/Profile.css
  client/src/css/Sidebar.css
  client/src/index.tsx
  client/src/pages/profile/Profile.tsx
  client/yarn.lock
Labels: frontend
