Repository hack4impact-uiuc/south-side-weekly, pull requests merged in 2021-11, with the labels that each got.

#162 Add and update interest functionality.
  api/src/api/index.ts
  api/src/api/interest.ts
  api/src/api/pitch.ts
  api/src/models/interest.ts
  api/src/models/pitch.ts
  api/src/models/user.ts
  api/src/utils/aggregate-utils.ts
  api/src/utils/enums.ts
  client/src/api/index.ts
  client/src/api/interest/index.ts
  client/src/api/interest/types.ts
  client/src/components/Dropdowns/InterestsSelect/index.tsx
  client/src/components/Dropdowns/TeamsSelect/index.tsx
  client/src/components/FieldTag/index.tsx
  client/src/components/FieldTag/styles.scss
  client/src/components/Modals/ApprovePitch/index.tsx
  client/src/components/Modals/ClaimPitch/index.tsx
  client/src/components/Modals/SubmitPitch/index.tsx
  client/src/components/Modals/User/index.tsx
  client/src/components/PitchCard/index.tsx
  client/src/components/ProviderWrapper/index.tsx
  client/src/components/Tables/Directory/index.tsx
  client/src/components/index.ts
  client/src/contexts/index.ts
  client/src/contexts/interests/context.ts
  client/src/contexts/interests/provider.tsx
  client/src/contexts/interests/types.ts
  client/src/contexts/teams/provider.tsx
  client/src/index.tsx
  client/src/pages/directory/helpers.ts
  client/src/pages/directory/index.tsx
  client/src/pages/pitchDoc/helpers.ts
  client/src/pages/pitchDoc/index.tsx
  client/src/pages/profile/index.tsx
  client/src/styles/colors.scss
  client/src/styles/styles.scss
  client/src/utils/constants.ts
  client/src/wizard/Onboard3/index.tsx
  common/index.d.ts
Labels: fullstack

#155 Create view pitch modal
  api/src/utils/aggregate-utils.ts
  client/src/api/index.ts
  client/src/api/pitch/index.ts
  client/src/api/pitch/types.ts
  client/src/components/Modals/RoleRow/index.tsx
  client/src/components/Modals/RoleRow/styles.scss
  client/src/components/Modals/ViewPitch/index.tsx
  client/src/components/Modals/ViewPitch/styles.scss
  client/src/components/index.ts
  client/src/pages/pitchDoc/index.tsx
  client/src/utils/helpers.ts
Labels: frontend

#188 Alias production
  api/src/api/auth.ts
  client/src/api/builders.ts
  client/src/api/index.ts
  client/src/api/urls.ts
  client/src/pages/login/index.tsx
  client/src/pages/login/styles.scss
  vercel.json
Labels: devops
